/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as DataUsageRouteImport } from './routes/data-usage'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardContactsRouteImport } from './routes/dashboard.contacts'
import { Route as DashboardCampaignsRouteImport } from './routes/dashboard.campaigns'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DashboardLeadsIndexRouteImport } from './routes/dashboard.leads.index'
import { Route as DashboardLeadsLeadIdRouteImport } from './routes/dashboard.leads.$leadId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const DataUsageRoute = DataUsageRouteImport.update({
  id: '/data-usage',
  path: '/data-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactsRoute = DashboardContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLeadsIndexRoute = DashboardLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLeadsRoute,
} as any)
const DashboardLeadsLeadIdRoute = DashboardLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => DashboardLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/data-usage': typeof DataUsageRoute
  '/gdpr': typeof GdprRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/leads': typeof DashboardLeadsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/leads/$leadId': typeof DashboardLeadsLeadIdRoute
  '/dashboard/leads/': typeof DashboardLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/data-usage': typeof DataUsageRoute
  '/gdpr': typeof GdprRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/leads/$leadId': typeof DashboardLeadsLeadIdRoute
  '/dashboard/leads': typeof DashboardLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/data-usage': typeof DataUsageRoute
  '/gdpr': typeof GdprRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/leads': typeof DashboardLeadsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/leads/$leadId': typeof DashboardLeadsLeadIdRoute
  '/dashboard/leads/': typeof DashboardLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/data-usage'
    | '/gdpr'
    | '/privacy'
    | '/refund'
    | '/support'
    | '/terms'
    | '/blog/$slug'
    | '/dashboard/campaigns'
    | '/dashboard/contacts'
    | '/dashboard/leads'
    | '/dashboard/settings'
    | '/blog/'
    | '/dashboard/'
    | '/dashboard/leads/$leadId'
    | '/dashboard/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/data-usage'
    | '/gdpr'
    | '/privacy'
    | '/refund'
    | '/support'
    | '/terms'
    | '/blog/$slug'
    | '/dashboard/campaigns'
    | '/dashboard/contacts'
    | '/dashboard/settings'
    | '/blog'
    | '/dashboard'
    | '/dashboard/leads/$leadId'
    | '/dashboard/leads'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/data-usage'
    | '/gdpr'
    | '/privacy'
    | '/refund'
    | '/support'
    | '/terms'
    | '/blog/$slug'
    | '/dashboard/campaigns'
    | '/dashboard/contacts'
    | '/dashboard/leads'
    | '/dashboard/settings'
    | '/blog/'
    | '/dashboard/'
    | '/dashboard/leads/$leadId'
    | '/dashboard/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DataUsageRoute: typeof DataUsageRoute
  GdprRoute: typeof GdprRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-usage': {
      id: '/data-usage'
      path: '/data-usage'
      fullPath: '/data-usage'
      preLoaderRoute: typeof DataUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contacts': {
      id: '/dashboard/contacts'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns': {
      id: '/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/leads/': {
      id: '/dashboard/leads/'
      path: '/'
      fullPath: '/dashboard/leads/'
      preLoaderRoute: typeof DashboardLeadsIndexRouteImport
      parentRoute: typeof DashboardLeadsRoute
    }
    '/dashboard/leads/$leadId': {
      id: '/dashboard/leads/$leadId'
      path: '/$leadId'
      fullPath: '/dashboard/leads/$leadId'
      preLoaderRoute: typeof DashboardLeadsLeadIdRouteImport
      parentRoute: typeof DashboardLeadsRoute
    }
  }
}

interface DashboardLeadsRouteChildren {
  DashboardLeadsLeadIdRoute: typeof DashboardLeadsLeadIdRoute
  DashboardLeadsIndexRoute: typeof DashboardLeadsIndexRoute
}

const DashboardLeadsRouteChildren: DashboardLeadsRouteChildren = {
  DashboardLeadsLeadIdRoute: DashboardLeadsLeadIdRoute,
  DashboardLeadsIndexRoute: DashboardLeadsIndexRoute,
}

const DashboardLeadsRouteWithChildren = DashboardLeadsRoute._addFileChildren(
  DashboardLeadsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCampaignsRoute: typeof DashboardCampaignsRoute
  DashboardContactsRoute: typeof DashboardContactsRoute
  DashboardLeadsRoute: typeof DashboardLeadsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCampaignsRoute: DashboardCampaignsRoute,
  DashboardContactsRoute: DashboardContactsRoute,
  DashboardLeadsRoute: DashboardLeadsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DataUsageRoute: DataUsageRoute,
  GdprRoute: GdprRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
